# Generated by Django 5.0.6 on 2024-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcategory',
            options={'verbose_name': 'pcategory', 'verbose_name_plural': 'pcategories'},
        ),
        migrations.AlterField(
            model_name='pcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
